name: Issue labeled

permissions: {}

on:
  issues:
    types:
      - labeled

jobs:
  handle-issue-label:
    if: startsWith(github.event.label.name, 'sign/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0

      - name: Create branch
        id: create-branch
        run: |
          # push main to the signing branch
          # * if branch didn't exist, it's created
          # * if branch did exist but can be fast forwarded, it is
          # * if branch exist but can't be fast-forward, the task fails
          git push origin main:${{ github.event.label.name }}
      
      - name: Comment on issue
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        with:
          script: |
            const body = `The branch ${{ github.event.label.name }} was created (or updated) for this
              signing event. Please make a pull request with your metadata changes to this branch.
            `
            github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            })

