name: Issue labeled

permissions: {}

on:
  issues:
    types:
      - labeled

jobs:
  handle-issue-label:
    if: startsWith(github.event.label.name, 'sign/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0

      - name: Create branch
        id: create-branch
        run: |
          if git ls-remote --exit-code --heads origin ${{ github.event.label.name }}; then
            # fast-forward merge main to the existing branch
            git merge --ff-only main:${{ github.event.label.name }}
            git push origin ${{ github.event.label.name }}
            echo "created=false" >> $GITHUB_OUTPUT
          else
            git push origin HEAD:${{ github.event.label.name }}
            echo "created=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Comment on issue
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        with:
          script: |
            const body
            if (${{ steps.create-branch.outputs.created }} == 'true') {
              body = `The branch ${{ github.event.label.name }} was created for this signing event.
                Please make a pull request with your metadata changes to this branch.
              `
            } else {
              body = `The branch ${{ github.event.label.name }} already exists and was fast-forwarded for this
                signing event. Please make a pull request with your metadata changes to this branch.
              `
            }
            github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            })

