name: Signing event

permissions: {}

on:
  push:
    branches:
      - 'sign/**'
  workflow_dispatch:

jobs:
  handle-branch-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0

      - name: Find fork point
        id: find-fork
        run: |
          git show-ref
          FORK=$(git merge-base origin/main $GITHUB_SHA)

          echo fork $FORK
          echo github_sha $GITHUB_SHA
          echo "fork=$FORK" >> $GITHUB_OUTPUT

      - name: Find the issue or open a new one
        id: find-issue
        if: steps.find-fork.outputs.fork != vars.GITHUB_SHA
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        with:
          script: |
            const repo = context.repo.owner + "/" + context.repo.repo
            const issues = await github.rest.search.issuesAndPullRequests({
              q: "label:${{github.ref_name}}+state:open+type:issue+repo:" + repo,
            })

            if (issues.data.total_count > 1) {
              core.setFailed("Found more than one issue with same label")
            }

            if (issues.data.total_count == 0) {
              console.log("Creating issue")
              const response = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "Signing event: ${{github.ref_name}}",
                body: "TODO: document signing event here",
                labels: ["${{github.ref_name}}"],
              })
              return response.data.number
            } else {
              console.log("Found existing issue")
              return issues.data.items[0].number
            }

      - name: Update signing status
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ steps.find-issue.outputs.result }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'TODO: Branch just moved, update signing status here'
            })
