name: Signing event

on:
  create:

jobs:
  handle:
    runs-on: ubuntu-latest
    if: ${{ vars.GITHUB_REF_TYPE == 'branch' }}
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Branch created $GITHUB_REF $GITHUB_SHA"
