name: Signing event

on:
  create:

jobs:
  handle:
    runs-on: ubuntu-latest
    if: |
      vars.GITHUB_REF_TYPE == 'branch' &&
      startsWith(vars.GITHUB_REF_NAME, 'sign/')
    steps:
      - name: Run a one-line script
        run: echo "Branch created $GITHUB_REF $GITHUB_SHA"
